add_library(lrclexec STATIC src/ExecutionContext.cpp)
add_library(lrclexec::lrclexec ALIAS lrclexec)
target_include_directories(lrclexec PUBLIC include)
target_compile_features(lrclexec PUBLIC cxx_std_17)
target_link_libraries(lrclexec PUBLIC lexec::lexec rclcpp::rclcpp rclcpp_action::rclcpp_action)
target_compile_options(lrclexec PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow -Werror=return-type)
if(LRCLEXEC_SANITIZE)
    target_compile_options(lrclexec PUBLIC -fsanitize=address,undefined -fno-omit-frame-pointer)
    target_link_options(lrclexec PUBLIC -fsanitize=address,undefined)
endif()
